import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable"; // Import as a plugin

export const generateReceipt = (order) => {
    const doc = new jsPDF();

    // Header Design
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229);
    doc.text("INVOICE / RECEIPT", 14, 20);

    // Order Details
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Order ID: ${order.id}`, 14, 30);
    doc.text(`Date: ${order.date}`, 14, 35);
    doc.text(`Customer: ${order.name}`, 14, 40);

    // Table Data
    const tableColumn = ["Description", "Details"];
    const tableRows = [
        ["Customer Email", order.email],
        ["Total Items", order.items.toString()],
        ["Shipping Method", order.method],
        ["Payment Status", order.status],
        ["Total Amount", order.amount],
    ];

    // FIXED LINE: Use autoTable(doc, {...}) instead of doc.autoTable
    autoTable(doc, {
        startY: 50,
        head: [tableColumn],
        body: tableRows,
        theme: 'striped',
        headStyles: { fillColor: [79, 70, 229], fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 }
    });

    // Footer
    const finalY = doc.lastAutoTable.finalY;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Hammad's Portfolio Dashboard", 14, finalY + 15);

    // Save PDF
    doc.save(`Receipt_${order.id}.pdf`);
};